# DEPLOYMENT
# =====================================================================================================================

url: ""
baseurl: ""

remote_theme: svrooij/just-the-docs@relative-everything


# METADATA
# =====================================================================================================================

title: Valheim Dedicated Server Help
description: |
  Unofficial support information about Valheim Dedicated Servers

permalink: pretty


# HEADER
# =====================================================================================================================

#logo: "/assets/images/just-the-docs.png"

search_enabled: true
search:
  heading_level: 6
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

heading_anchors: true
aux_links_new_tab: false
nav_sort: case_sensitive


# FOOTER
# =====================================================================================================================

back_to_top: true
back_to_top_text: "Back to Top"

footer_content: |
  Unoffical support information compiled by volunteers from the <a href=\"https://discord.gg/U7Ng93FER8\">Valheim Discord</a>.
  No information is guaranteed to be correct, all advice is followed at your own risk.

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/pmarsceill/just-the-docs" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

color_scheme: light


# PLUGINS
# =====================================================================================================================

# plugins:
#  - jekyll-seo-tag

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking: UA-2709176-10
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [ ]
  blanklines: false
  profile: false
  # ignore:
  #   envs: all